DROP DATABASE IF EXISTS charity_kitchen;
DROP USER IF EXISTS `springuser`;
CREATE DATABASE IF NOT EXISTS charity_kitchen CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `springuser` IDENTIFIED WITH mysql_native_password BY '123456';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `charity_kitchen`.* TO `springuser`;